name: Deploy MERN Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./client

      - name: Build Frontend
        run: npm run build
        working-directory: ./client

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build